### ISSUE TITLE
Progress Bar seems to block theme from working

### ISSUE THREAD

**Issue by BenParizek** [pixelandtonic/vuepress-theme-craftdocs#1]
I've followed the docs and have VuePress setup with the Craft Docs theme. I've added the theme and additional `markdown` code in my config.js file:

```
module.exports = {
    ...
    theme: 'craftdocs',
    ...
    markdown: {
        anchor: { level: [2, 3] },
        config(md) {
            let markup = require('vuepress-theme-craftdocs/markup');
            md.use(markup);
        }
    }
};
```
When I run `npm run docs:dev` with the Craft theme enabled I get the following error:

```
WARNING in ./node_modules/vuepress-theme-craftdocs/Layout.vue?vue&type=script&lang=js (./node_modules/cache-loader/dist/cjs.js??ref--3-0!./node_modules/babel-loader/lib??ref--3-1!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuepress-theme-craftdocs/Layout.vue?vue&type=script&lang=js)
105:50-69 "export 'pathToComponentName' was not found in '@app/util'
 @ ./node_modules/cache-loader/dist/cjs.js??ref--3-0!./node_modules/babel-loader/lib??ref--3-1!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuepress-theme-craftdocs/Layout.vue?vue&type=script&lang=js
 @ ./node_modules/vuepress-theme-craftdocs/Layout.vue?vue&type=script&lang=js
 @ ./node_modules/vuepress-theme-craftdocs/Layout.vue
 @ ./node_modules/vuepress/lib/app/.temp/routes.js
 @ ./node_modules/vuepress/lib/app/app.js
 @ ./node_modules/vuepress/lib/app/clientEntry.js
 @ multi ./node_modules/vuepress/lib/app/clientEntry.js
```

I've created a short video that walks through the steps I'm taking to get the above error.
http://share.barrelstrength.co/083X3W0f0v2c

Commenting out the the "configure progress bar" code Craft Docs theme `Layout.vue` seems to fix the immediate issue, but doesn't solve the underlying issue if a progress bar is desired. It appears `pathToComponentName` is not defined in my environment. I've had two other people confirm the issue exists in their environments as well.

**Comment by brandonkelly** [comment]
Maybe you need to update Node / NPM / Yarn? Works on our end.
