### ISSUE TITLE
Question: can this theme be used for regular contents?

### ISSUE THREAD

**Issue by amimas** [pixelandtonic/vuepress-theme-craftdocs#10]
I came across this tool while looking for api documentation using vuepress. It looks ereally nice but the demo/sample site only shows sample api docs.

Does this theme allow serving regular docs/guides in addition to api references?

**Comment by mattstein** [comment]
Yes @amimas, we’re using this theme to power all of the [Craft CMS](https://docs.craftcms.com/v3/) and [Craft Commerce](https://docs.craftcms.com/commerce/v3/) documentation and API docs as well as the [Craft CMS Tutorial](https://docs.craftcms.com/tutorial/). 🙂
