### ISSUE TITLE
Error: Cannot resolve theme: craftdocs.

### ISSUE THREAD

**Issue by bonniss** [pixelandtonic/vuepress-theme-craftdocs#12]
Hello, after installing this theme, I run `yarn docs:dev` and get this error. At the time of the issue, I'm using vuepress@1.4.

**Comment by mattstein** [comment]
@bonniss The theme was previously based on VuePress 0.14.4, but we’ve just updated it for VuePress 1.4. Would you mind trying the latest version of this theme and seeing if it resolves your issue?

**Comment by bonniss** [comment]
The issue has gone. Thank you for supporting, @mattstein !
