### ISSUE TITLE
split page views

### ISSUE THREAD

**Issue by silviucpp** [pixelandtonic/vuepress-theme-craftdocs#13]
Hello,

Support for split page views was removed ?

There is still the following text in readme : "Adds support for code language toggles and split page views." but other references were removed 

Silviu

**Comment by mattstein** [comment]
Sorry for the confusion @silviucpp, I stumbled through this release. But yes, we removed the custom split page views and the storage handler they relied on.

**Comment by silviucpp** [comment]
So basically there is no way with the new version to implement something like this page:

https://docs.api.craftcms.com/plugin-licenses.html ??

Silviu

**Comment by mattstein** [comment]
Good point, @silviucpp. 🤦 

Will get this added to a new release.

**Comment by silviucpp** [comment]
Nice :) this was the most powerful feature of the theme.

**Comment by mattstein** [comment]
It’s back now in 2.0.1 of this theme—thanks for championing split view support @silviucpp!
