### ISSUE TITLE
Code Toggles improvements

### ISSUE THREAD

**Issue by silviucpp** [pixelandtonic/vuepress-theme-craftdocs#14]
Hello,

Congrats for this awesome theme first. While using this theme I found out some things that can be improved and I would like to share them with you:

In Code Toggles sometimes might be useful that I can make same code blocks visible for multiple languages tab's and also to specify with what language to be highlighted. 

Let me give you an example : 

I have 5 languages and I want to do something like showing REQUEST code RESPONSE object. Of course the  request blocks will be different from language to language but RESPONSE might be a json which no matter  how you do the request will be the same. 

Without a way to bind the RESPONSE to all languages I need to do lot of duplicated text

Will be nice to have something like:

````markdown
::: code

``` json -> php,curl,java

.. json here

```

or 

``` json -> all

.. json here

```

:::
````

Which will make that code visible in first case for php curl and java and also will highlight it as json, or in the second case will make it visible to all code blocks.

**Comment by brandonkelly** [comment]
I’m not sure I’m following. Why not just place the response example in its own `json` code block _after_ the example request code toggles?

````markdown
#### Request

::: code

```php
// example...
```

```curl
# example...
```

```java
// example...
```

:::

#### Response

```json
{
    "...": "..."
}
```
````

**Comment by silviucpp** [comment]
If you are doing like that then when you have Java selected as language you won't see the response :)

**Comment by brandonkelly** [comment]
I guess you are referring to split views? Even then, the language selector will only affect code blocks within language toggles.

See an example here: http://docs.api.craftcms.test/plugin-licenses.html
