### ISSUE TITLE
craftdocs api theme

### ISSUE THREAD

**Issue by pratik149** [pixelandtonic/vuepress-theme-craftdocs#15]
Hey team, I liked the documentation theme developed by you people for Vuepress. Thank you for making it opensource. But more than that I really liked the theme of your API docs which is hosted on https://docs.api.craftcms.com/

May I know whether api docs is also developed using Vuepress or is it anything else? If yes, then is there any chances of making its vuepress theme opensource too, or is it going to remain closed-source only?

**Comment by mattstein** [comment]
Glad you’re liking it, @pratik149! The Craftnet API Documentation uses the same VuePress theme as the rest of the documentation. Visually, the most significant difference is that we’re using the split code views mentioned in the readme: https://github.com/pixelandtonic/vuepress-theme-craftdocs#split-views

**Comment by pratik149** [comment]
Thank you for the prompt reply, @mattstein. And that's awesome! I didn't know that split code feature could bring this much change in the whole UI of default Vuepress theme, also It's responsive too! really commendable!

Again thank you for making it open source. I starred the repo, will sure consider using it in my project's documentation.
