### ISSUE TITLE
Craftnet API documentation

### ISSUE THREAD

**Issue by sdwru** [pixelandtonic/vuepress-theme-craftdocs#16]
Hello,

Do you know what software is used for the craftnet API documentation?  Is it also using vuepress?

https://docs.api.craftcms.com/

**Comment by mattstein** [comment]
Hi @sdwru. Yes, the Craftnet API documentation also use this VuePress theme. They look a bit different because many pages take advantage of the [Split Views feature mentioned in the readme](https://github.com/pixelandtonic/vuepress-theme-craftdocs#split-views).
