### ISSUE TITLE
VuePress v2 compatibility

### ISSUE THREAD

**Issue by jmaneyrol69** [pixelandtonic/vuepress-theme-craftdocs#26]
### Description

Since VuePress v1 is no longer maintained and v2 (vuepress@next) should be stable by the beginning of 2022, are there any plans to port this theme to VuePress v2?

**Comment by mattstein** [comment]
We don’t have any formal plan to port this theme to VuePress 2, though it is still in use for some of our live documentation so we may need to revisit later.
