### ISSUE TITLE
Add support for override.styl

### ISSUE THREAD

**Issue by BenParizek** [pixelandtonic/vuepress-theme-craftdocs#3]
The default VuePress Theme supports overriding styles via:
https://vuepress.vuejs.org/default-theme-config/#simple-css-override

It would be nice to be able to use the Craft Docs theme and still have the option to override a few styles. Currently, the `override.styl` file stops working once switching over to the Craft Docs theme.

Example overrides in `override.styl`:

```
$accentColor = #449211

.sidebar-links a.active {
  ...
}
```

**Comment by brandonkelly** [comment]
Yeah I’d be fine with this. Not really sure what would be involved though; feel free to PR it.

**Comment by christian-schlichtherle** [comment]
Looks like this can be closed now?!

**Comment by mattstein** [comment]
This should be settled now with v2.0.0 of the theme, if it wasn’t already. Closing, but let me know if there are any issues!
