### ISSUE TITLE
Google Analytics Tracking code never gets output

### ISSUE THREAD

**Issue by BenParizek** [pixelandtonic/vuepress-theme-craftdocs#4]
It appears that you can add a Google Analytics tracking code in the Theme Config:
https://github.com/craftcms/docs/blob/v3/docs/.vuepress/config.js#L6

The Craft docs do this and we've tried to do it as well. However, I'm not seeing any tracking code output in the Craft docs or in our tests.

**Comment by brandonkelly** [comment]
I’m not sure how it works off the top of my head, but it works for us, at least in production.

**Comment by BenParizek** [comment]
I can confirm this is working for us too. In my initial tests I wasn't seeing any data in Google Analytics nor any tracking code in the source but it seems it is working now, so perhaps the tracking code is in one of those hundreds of js files VuePress generates!
