### ISSUE TITLE
Template expressions do not work

### ISSUE THREAD

**Issue by christian-schlichtherle** [pixelandtonic/vuepress-theme-craftdocs#8]
According to the Vuepress documentation, when putting the following into a Markdown file:

    {{ 1 + 1 }}

then the generated HTML should contain `2`, not `{{ 1 + 1 }}`.
Unfortunately, as soon as the craftdocs theme is added, this is rendered verbatim.

**Comment by brandonkelly** [comment]
This is expected behavior. Just updated the readme with a list of changes this theme has over the default theme, including how interpolation is disabled.
