### ISSUE TITLE
Support for Vuepress 1.x.x

### ISSUE THREAD

**Issue by oniel1921** [pixelandtonic/vuepress-theme-craftdocs#9]
@brandonkelly are you considering adding this theme to Vuepress 1.x.x going forward? For example, by [extending](https://vuepress.vuejs.org/theme/option-api.html#extend) the vuepress-default theme since both this theme and the vuepress theme share so many components?

**Comment by khalwat** [comment]
Also interested in this; I'm using VuePress, and am deciding whether or not to use VuePress 1.0.x and the default theme (or make my own) or use the Craft theme.

In this case, it's for documentation for my plugins, so using the Craft theme has some nice benefits.

**Comment by mattstein** [comment]
Just released v2.0.0 of this theme with support for VuePress 1.4!
